cawsr:
  debug: false
  carla:
    host: 127.0.0.1
    fidelity: 'High'
    port: 2000
    timeout: 20
    fixed_delta_seconds: 0.05 # update rate 1 / FPS
    traffic_manager:
      seed: 0
      port: 8001
      #active: true # part of scenario definition

  initialisation_budget: 500 # ticks
  agent: srunner/autoagents/autoware_agent
  mode: 'benchmark' # benchmark or algorithm

  benchmark:
    scenarios: scenarios/examples # directory
    random_sampling: true # pick random scenario or ordered

  algorithm:
    initial_definition: scenarios/examples/example_scenario.json
    seed: 10
    runs: 50
    path: algorithms/random_search
    args:
      lanelet2: algorithms/resources/Town01.osm
